const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const ProductCustom = new Schema({
    uuid: { type: String, unique: true, dropDups: true },
    category: String,
    colorway: String,
    condition: String,
    minimumBid: String,
    gender: String,
    media_imageUrl: String,
    releaseDate: String,
    releaseTime: Number,
    belowRetail: String,
    retailPrice: String,
    title: String,
    name: String,
    value: String,
    urlKey: String,
    lowestAsk: String,
    lowestAskSize: String,
    productUuid: String,
    parentLowestAsk: String,
    numberOfAsks: String,
    salesThisPeriod: String,
    salesLastPeriod: String,
    highestBid: String,
    highestBidSize: String,
    numberOfBids: String,
    annualHigh: String,
    annualLow: String,
    deadstockRangeLow: String,
    deadstockRangeHigh: String,
    volatility: String,
    deadstockSold: String,
    pricePremium: String,
    averageDeadstockPrice: String,
    lastSale: String,
    lastSaleSize: String,
    salesLast72Hours: String,
    changeValue: String,
    changePercentage: String,
    totalDollars: String,
    updatedAt: String,
    lastLowestAskTime: String,
    lastHighestBidTime: String,
    lastSaleDate: String,
    createdAt: String,
    deadstockSoldRank: String,
    pricePremiumRank: String,
    averageDeadstockPriceRank: String,
    tags_t_shirts: String,
});

var ProductCustoms = mongoose.model("product_custom", ProductCustom);
module.exports = ProductCustoms;